# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Match terms
#' @description Implimented in C++
#' @export
match <- function(term_vector, pdf_tdm, term_tdm, thresholds, pdf_index, terms, sentences) {
    .Call('goldi_match', PACKAGE = 'goldi', term_vector, pdf_tdm, term_tdm, thresholds, pdf_index, terms, sentences)
}

