# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
match <- function(term_vector, terms, sentences, pdf_tdm, term_tdm, thresholds) {
    .Call('mineR_match', PACKAGE = 'mineR', term_vector, terms, sentences, pdf_tdm, term_tdm, thresholds)
}

